### ISSUE TITLE
Define all possible fields for yaml file

### ISSUE THREAD

**Issue by wigging** [KnoxDevs/directory#11]
Have a base template or schema defined for each type of yaml file: organizer, location, bloggers, etc. Or clearly define this schema in the README file.

For example, the yaml file for a location would look like:

```yaml
name: Technology Cooperative

description: >
    The Technology Cooperative was founded to create a technology-focused community that will provide computer-related technology access and awareness. It also provides co-working space most weekdays until 6pm.

links:
    website: http://techco.org/co-working-space/
    github:
    twitter: TechCoop
    facebook:

address:
    street: 13 Emory Pl, Knoxville, TN 37917
    latitude: 35.9747
    longitude: -83.922917
```

Notice that the `github:` and `facebook:` values are left blank and those fields are not removed from the yaml file. As such, all yaml files in a folder will have the same fields; even if some fields are empty.
